### ISSUE TITLE
composer install no package

### ISSUE THREAD

**Issue by EvansYe2** [zacksleo/yii2-backend#8]
- zacksleo/yii2-backend 1.0.0 requires zacksleo/yii2-metronic ^2.0 -> satisfiable by zacksleo/yii2-metronic[2.0.1, 2.0.10, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0].
    - zacksleo/yii2-backend 1.0.1 requires zacksleo/yii2-metronic ^2.0 -> satisfiable by zacksleo/yii2-metronic[2.0.1, 2.0.10, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0].
    - zacksleo/yii2-backend 1.0.2 requires zacksleo/yii2-metronic ^2.0 -> satisfiable by zacksleo/yii2-metronic[2.0.1, 2.0.10, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0].
    - zacksleo/yii2-backend 1.0.3 requires zacksleo/yii2-metronic ^2.0 -> satisfiable by zacksleo/yii2-metronic[2.0.1, 2.0.10, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0].
    - zacksleo/yii2-backend 1.0.4 requires zacksleo/yii2-metronic ^2.0 -> satisfiable by zacksleo/yii2-metronic[2.0.1, 2.0.10, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0].
    - zacksleo/yii2-backend 1.0.5 requires zacksleo/yii2-metronic ^2.0 -> satisfiable by zacksleo/yii2-metronic[2.0.1, 2.0.10, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0].
    - zacksleo/yii2-backend 1.0.6 requires zacksleo/yii2-metronic ^2.0 -> satisfiable by zacksleo/yii2-metronic[2.0.1, 2.0.10, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0].
    - zacksleo/yii2-backend 1.0.7 requires zacksleo/yii2-metronic ^2.0 -> satisfiable by zacksleo/yii2-metronic[2.0.1, 2.0.10, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0].
    - zacksleo/yii2-backend 1.0.8 requires zacksleo/yii2-metronic ^2.0 -> satisfiable by zacksleo/yii2-metronic[2.0.1, 2.0.10, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0].
    - zacksleo/yii2-backend 1.0.9 requires zacksleo/yii2-metronic ^2.0 -> satisfiable by zacksleo/yii2-metronic[2.0.1, 2.0.10, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0].
    - zacksleo/yii2-backend dev-docs requires zacksleo/yii2-metronic ^2.0 -> satisfiable by zacksleo/yii2-metronic[2.0.1, 2.0.10, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0].
    - zacksleo/yii2-backend dev-master requires zacksleo/yii2-metronic ^2.0 -> satisfiable by zacksleo/yii2-metronic[2.0.1, 2.0.10, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0].
    - zacksleo/yii2-backend v0.1.0 requires zacksleo/metronic ~4.7.1 -> no matching package found.
    - zacksleo/yii2-backend v0.0.1 requires zacksleo/metronic ~4.7.1 -> no matching package found.
    - zacksleo/yii2-metronic 2.1.0 requires bower-asset/bootstrap-markdown ^2.1 -> no matching package found.
    - zacksleo/yii2-backend 0.2.4 requires zacksleo/metronic ^4.7 -> no matching package found.
    - zacksleo/yii2-backend 0.2.3 requires zacksleo/metronic ~4.7.1 -> no matching package found.
    - zacksleo/yii2-backend 0.2.2 requires zacksleo/metronic ~4.7.1 -> no matching package found.
    - zacksleo/yii2-backend 0.2.1 requires zacksleo/metronic ~4.7.1 -> no matching package found.
    - zacksleo/yii2-metronic 2.0.9 requires bower-asset/bootstrap-markdown ^2.1 -> no matching package found.
    - zacksleo/yii2-metronic 2.0.8 requires bower-asset/bootstrap-markdown ~2.10.0 -> no matching package found.
    - zacksleo/yii2-metronic 2.0.7 requires bower-asset/bootstrap-markdown ~2.10.0 -> no matching package found.
    - zacksleo/yii2-metronic 2.0.6 requires bower-asset/bootstrap-markdown ~2.10.0 -> no matching package found.
    - zacksleo/yii2-metronic 2.0.5 requires bower-asset/bootstrap-markdown ~2.10.0 -> no matching package found.
    - zacksleo/yii2-metronic 2.0.4 requires bower-asset/bootstrap-markdown ~2.10.0 -> no matching package found.
    - zacksleo/yii2-metronic 2.0.3 requires bower-asset/bootstrap-markdown ~2.10.0 -> no matching package found.
    - zacksleo/yii2-metronic 2.0.2 requires bower-asset/bootstrap-markdown ~2.10.0 -> no matching package found.
    - zacksleo/yii2-metronic 2.0.10 requires bower-asset/bootstrap-markdown ^2.1 -> no matching package found.
    - zacksleo/yii2-metronic 2.0.1 requires bower-asset/bootstrap-markdown ~2.10.0 -> no matching package found.
    - zacksleo/yii2-backend 0.2.0 requires zacksleo/metronic ~4.7.1 -> no matching package found.
    - Installation request for zacksleo/yii2-backend *@dev -> satisfiable by zacksleo/yii2-backend[0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, dev-docs, dev-master, v0.0.1, v0.1.0].

**Comment by zacksleo** [comment]
`zacksleo/metronic` 是私有package, 需要自己提供, 这里面存放的metronic资源
